[project]
org-name="ballerinax"
version="0.99.0"

[platform]
target = "java8"

[[platform.libraries]]
module = "cassandra"
path = "../cassandra-utils/target/original-cassandra-utils-0.99.0.jar"
artifactId = "cassandra-utils"
version = "0.8.5"
groupId = "org.ballerinalang"

[[platform.libraries]]
module = "cassandra"
path = "../cassandra-utils/target/classes/lib/cassandra-driver-core-3.6.0.jar"
artifactId = "cassandra-driver-core"
version = "3.6.0"
groupId = "com.datastax.cassandra"
